# popclip extension to search ones
name: ones
icon: search filled et
url: https://et.baishancloud.com/project/#/home/team/EgDNxqWv/search/wiki/page?backUrl=/home/wiki/space/category/all&searchText=***